[gcp_service_account]
type = "service_account"
project_id = "streamlit-data-project"
private_key_id = "5b13b866f994501ae89ab3adb720f6087ba5f47c"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCxIhrVNBCazawY
OLxXmbtz9EZ0GGCXL8fLwFYVa8zjOzhcLmlgkmtCBHvWzA2v2Lo05y0Nk4YJzR/W
KoElvc3HBv9N1CNFnYklbeKML3pvw+uqX2ky00WahrbMOiqI6dRt8GbM1aMPWOMt
xIcbnqcWW6si61S0NxqYbPW++vHK+2Bseag8CwIICqF3vOBvXiMeMQEkx6hfOQKa
xUAjkT37QexLR8z2OTmUaocss6RdpO5LGjgXcvgRvpcrii7Id4LymN1y28Zmmk6M
kpU6pF/LW/xdOhJyzVjofZhrQVsfCnpShxmEPJQ2+6x3K3J17Rx4zegPtcXE8jeP
UhWE6rWDAgMBAAECggEAKrnPPx4P40c4+56zz22FibKiS96VbeJYjw0VtpUKFsVy
EsofIOwwcvwh4u3VX1UnlRsuAthSvIp942rdO/1MZXWKn3tMBr65Fg4rVyUco1je
v3nEJj5Py7Yy4ZAmMmA0nVAfe8kMS+dk5OVCsabTJtF1tjaNd+rSv3GI1UgyioMw
4C206nVfGuitbzNCvvslQ7C/LQmipq84q8zIijNEUeY+yJ5dnQ4ZWGp/FvkkzY+w
aWg0wqNGFb+7OaY3YAhYyOOJyAWF4adsat2NdmBLBnRs4ezlObRIyzqD01Rv9vWG
t0i9D4yMr05GWSOPtroSc4iS/CCBexc40J33nKseAQKBgQDoVk97FeagEWT5OuVQ
/9diprWSrRM4+gbHFgBgon+QCucUIQu4q8+qTDB/wzr+ZNCyM7lhRt1bIWpB4z3j
TQtmRT3wM5IvUq5QENrCYYc20I4Cdv5gZefHOqe+uU4dCyVAcPM2ROiq+1KKegFg
OGYRK7SzP4JRZHcQGEVZ2N+lHQKBgQDDLHianrhwNb5lhNz4Vq+fUdBfeaKPx15K
oKodUXX6jTQ53hpLS8b+l/haTZz99ef1ubND+7m/QRPMlHPsB1iJOVVxNKzc6821
ovDzsP0CAQg4wpOtR4+BGpuQ65kE45y2kHw9BisIZK57hUucsnyH+LWaTtlSw5Q5
ecpEkZHjHwKBgQCRqKLVuOpIif8y3UCtImhnGbsWBNnbS6z6HYoJC3dL1/n9PaZ6
lYRw8KkrQDt5B71rK1BaczINkwpp2kyPd1rhOCHXuI06i+xql9Z+LOS3cdLGKtHZ
n6nK1rQZt1UIklc9alKgQF1Z7IxX8ptwNouO0kbMZdGOs5yNg5ne9T9o5QKBgGEe
KOkvn7FeXN6hTV9Zq0xI5roLiaOn3jieV+f82AsT5nABH+5lx6B6OH+e7UbF7WWt
wRFMGjKcDGEZYdGKGjk2SVjqkDXiNFt0uBda85rirpen4tovqK3icpSbV2pCZIHH
xbqL7i/gAZ6/Rk+z1RnH3X3qTGPNpF0xSD/0e7abAoGAZ2oeuxQKC/v1bxsFh4C7
4ygJ/ZkvKzdIdo4gwwfA2oLU3DsZUImAbpnEky//HhADBL2JHasgM1iR3oJJo6ko
p6UnR5Td4EIFyaroGpN8Pkq+YKG5ihf3ApPQwUci7LuQsaOmn1Nox/ro++q1EHmy
BbqN3yfld21cSHkyhaSivtA=
-----END PRIVATE KEY-----
"""
client_email = "drive-files-streamlit@streamlit-data-project.iam.gserviceaccount.com"
client_id = "108725030250163219642"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/drive-files-streamlit%40streamlit-data-project.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
